### ISSUE TITLE
The plugin cannot be set-up

### ISSUE THREAD

**Issue by pukakuka** [Mechazawa/Emergency_stop_simplified#6]
_Hello, I tried setting the BCM pin multiple times, but nothing was happening. Then I took a look into the logs and found this:_

> 2020-12-04 00:15:00,341 - octoprint.plugins.emergencystopsimplified - INFO - Setting up button.
> 2020-12-04 00:15:00,343 - octoprint.plugins.emergencystopsimplified - INFO - Using Board Mode
> 2020-12-04 00:15:00,345 - octoprint.server.api.settings - ERROR - Could not save settings for plugin Emergency Stop Simplified (0.1.1)
> Traceback (most recent call last):
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/server/api/settings.py", line 1034, in _saveSettings
>     plugin.on_settings_save(data["plugins"][plugin_id])
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/__init__.py", line 1890, in wrapper
>     return f(*args, **kwargs)
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_emergencystopsimplified/__init__.py", line 53, in on_settings_save
>     self._setup_button()
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_emergencystopsimplified/__init__.py", line 59, in _setup_button
>     GPIO.setmode(GPIO.BCM)
> ValueError: A different mode has already been set!

_Am I missing something ?_

Tried reinstalling the plugin with cleaning the stored data, tried different GPIO ports.

_I'm running Octoprint 1.5.0 on a Pi._

**Comment by JetztGo** [comment]
I had the same problem, but I fixed it. You have to change in the in the _init_ file at line 57 GPIO.setmode(GPIO.BCM) to GPIO.setmode(GPIO.BOARD).
 
![image](https://user-images.githubusercontent.com/77749274/105220892-ab0df380-5b58-11eb-879a-7738a47feb7c.png)

after that you have to upload the new file on your raspberry, I used WinSCP for that.
![image](https://user-images.githubusercontent.com/77749274/105221583-97af5800-5b59-11eb-9629-6c2f9a072848.png)

**Comment by KalixtShawxo** [comment]
I don't know if this is the same issue....but I have everything connected properly, ground and GPIO27 to a closed switch, but as soon as I start a print job it registers as the button being pressed.
